name: "42Crunch API Conformance Scan: check-sqg"
description: "The API Conformance Scan action adds an automatic static Conformance Scan to your workflows"
inputs:
  api-token:
    description: "The API token to access 42Crunch Platform. Please create free account at https://platform.42crunch.com/register and follow hese steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm"
    required: true
  platform-url:
    description: "42Crunch platform URL"
    required: false
    default: "https://platform.42crunch.com"
  audit-report-path:
    required: false
    description: "Path to JSON report from audit step"
  api-ids:
    required: false
    description: "UUID or list UUID of API"

branding:
  icon: "eye"
  color: "purple"
runs:
  using: "docker"
  image: "../Dockerfile"
  args:
    - "42c"
    - "scan"
    - "--api-key=${{ inputs.api-token }}"
    - "--platform-url=${{ inputs.platform-url }}"
    - "check-sqg"
    - "--report-path=${{ inputs.audit-report-path }}"
    - "--api-id=${{ inputs.api-ids }}"
    # - "a=${{ inputs.api-ids }}"
    # - ${{ replace(' ', ' ', inputs.my-input) }}
    # - ${{ join(' --api-id=', replace(' ', ' --api-id=', inputs.api-ids)) }}
